# Generated by Django 4.0.3 on 2022-05-05 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='users_like',
        ),
        migrations.AddField(
            model_name='pin',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='boards.board'),
            preserve_default=False,
        ),
    ]
