# Generated by Django 4.0.3 on 2022-05-05 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('cover', models.ImageField(default='boards/default.png', upload_to='boards')),
                ('is_private', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('pins', models.ManyToManyField(blank=True, related_name='pins', to='posts.pin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
